# Generated by Django 3.2.18 on 2024-01-03 12:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="useraccount",
            name="name",
        ),
        migrations.AlterField(
            model_name="useraccount",
            name="username",
            field=models.CharField(max_length=255),
        ),
    ]
