# Generated by Django 3.2.18 on 2024-01-03 12:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_auto_20240103_1209"),
    ]

    operations = [
        migrations.AlterField(
            model_name="useraccount",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
